id: P003308
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6081
  title: གཞུང་ས་དགའ་ལྡན་ཕོ་བྲང་སྐབས་ཀྱི་ཁྲིམས་སྲོལ་བཅའ་ཆིངས་བདམས་བསྒྲིགས།
  author: ''
  volumes:
    9d42236fc0c148dfb878362599aaf440:
      image_group_id: I2KG209834
      title: ''
      volume_number: 1
      total_pages: 665
