id: IA2E4FB74
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T03:22:34+00:00'
last_modified: '2022-06-07T18:58:59.978467+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6081
  title: གཞུང་ས་དགའ་ལྡན་ཕོ་བྲང་སྐབས་ཀྱི་ཁྲིམས་སྲོལ་བཅའ་ཆིངས་བདམས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    8C35:
      image_group_id: I2KG209834
      title: ''
      total_pages: 665
      order: 1
      base_file: 8C35.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
